Quiz/quiz1.html
Quiz/quiz2.html
Quiz/quiz3.html

HTML Inicial para trabalhar simultaneamente nas estruturas de HTML - 1 index  / 3 Quiz

HTML Inicial para trabalhar simultaneamente

---

index.html

Criação da estrutura de formulário da página inicial

estrutura pagina inicial

---

Quiz/quiz2.html

Estrutura Quiz-CSS

---

Quiz/quiz2.html

Atualizei o parenteses pelo código especial - &#x29.

quiz2 atualizado

---

index.html
style/main.css

css da pagina inicial

---

Quiz/quiz1.html
Quiz/ranking.html
style/ranking.css

ranking-html

---

Quiz/ranking.html
style/ranking.css

CSS-Ranking

---

Quiz/quiz1.html
Quiz/quiz2.html
Quiz/quiz3.html
style/quizes.css

Estruturei o layout de css dos quiz parecido com o modelo do professor.
Deixei as estruturas html dos quiz no mesmo formato de código

estrutura layout quiz

---

.vscode/settings.json
index.html
script/quiz1.js

alteração do index.html e transferência do quizz1 (html) para JS

alteração html e quiz1.js

---

index.html
ranking.css
style/darkmode.css

Mais cores adicionado no gradiente do dark mode

update do darkmode

---

script/resultados.js
script/script.js

Ordenação dos dados da tabela Resultados por data (hora)

ordenação dos dados da tabela de resultados

---

index.html
script/cron.js
script/resultados.js
script/script.js

inclusão de coluna hora na tabela de resultado + alteração do timer

inclusão de coluna hora na tabela de resultados

---

index.html
script/script.js

inclusão do botão reiniciar que limpa os campos nome/ tema + correção da pontuação

add botão reiniciar

---

index.html
script/script.js

alterações

---

index.html
script/resultados.js
script/script.js

verificar calcularMedia (está comentado)

teste btnFinalizar

---

index.html
script/script.js
style/ranking.css

Inclusão do botão resultado e alteração do botão finalizar com funções

add botão resultado

---

index.html
style/main.css

Timer estava obstruindo botão dark mode. Foi passado para o lado esquerdo

Timer para o lado esquerdo

---

index.html
style/btns.css
style/darkmode.css
style/quizes.css

Estilização dos três quiz foram adicionados 
Estilização dos botões do quiz foram adicionados

estilizacaoQuiz

---

index.html
style/darkmode.css
style/main.css
style/ranking.css
style/ranking2.css

css aplicação da paleta definida

cssresultpaleta

---

index.html
style/darkmode.css
style/main.css

Bug de mudar o tamanho do timer foi corrigido.

timerCorrigido

---

index.html
style/btns.css

Css-button

---

style/btns.css

css-buttons
